# 服务器配置
server:
  port: ${plugin.pluginPort:8081}
  servlet:
    context-path: /

# 插件配置
plugin:
  name: embedding-plugin
  version: 0.1.0
  description: 基于DJL和PyTorch的文本向量化插件，支持多语言
  serverHost: localhost
  serverPort: 8080
  pluginPort: 8081
  modelType: LaBSE
  # 添加模型文件路径配置
  modelPath: models/LaBSE.pt

# 日志配置
logging:
  level:
    root: INFO
    com.owiseman: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Spring配置
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false